version: '3.4'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

      MONGO_READ_USERNAME: ${MONGO_READ_USERNAME}
      MONGO_READ_PASSWORD: ${MONGO_READ_PASSWORD}

      MONGO_READWRITE_USERNAME: ${MONGO_READWRITE_USERNAME}
      MONGO_READWRITE_PASSWORD: ${MONGO_READWRITE_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: >
      "--auth"
volumes:
  mongo-data:
