server:
  port: 8000

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@localhost:27017/start?authSource=admin
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${auth0.clientId}
            client-secret: ${auth0.clientSecret}
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/

spotify:
  clientId: ${SPOTIFY_CLIENT_ID}
  clientSecret: ${SPOTIFY_CLIENT_SECRET}
  redirectUri: http://localhost:8000/widgets/spotify/auth/callback
  apiBaseUrl: https://api.spotify.com/v1
  scopes: user-read-currently-playing

todoist:
  clientId: ${TODOIST_CLIENT_ID}
  clientSecret: ${TODOIST_CLIENT_SECRET}
  redirectUri: http://localhost:8000/widgets/todoist/auth/callback
  apiBaseUrl: https://api.todoist.com/rest/v2
  scopes: data:read

unsplash:
  clientId: ${UNSPLASH_CLIENT_ID}
  clientSecret: ${UNSPLASH_CLIENT_SECRET}
  redirectUri: http://localhost:8000/widgets/unsplash/auth/callback
  apiBaseUrl: https://api.unsplash.com
  scopes: write_likes+public

instagram:
  clientId: ${INSTAGRAM_CLIENT_ID}
  clientSecret: ${INSTAGRAM_CLIENT_SECRET}
  redirectUri: http://localhost:8000/widgets/instagram/auth/callback
  apiBaseUrl: https://graph.instagram.com/v19.0

encryption:
  secretKey: ${SECRET_KEY}

auth0:
  domain: ${AUTH0_DOMAIN}
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: ${AUTH0_AUDIENCE}
