server:
  port: 8000

frontend:
  base-url: ${FRONTEND_BASE_URL}

spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@localhost:27017/start?authSource=admin
  devtools:
    restart:
      enabled: ${DEV_MODE:false}
      additional-paths: src/main

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expires-in: ${JWT_EXPIRATION}

logging:
  level:
    io.github.antistereov.start: ${LOG_LEVEL:DEBUG}

spotify:
  service-name: Spotify
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
  redirect-uri: ${FRONTEND_BASE_URL}/callback/spotify
  apiBase-url: https://api.spotify.com/v1
  scopes: user-read-currently-playing user-read-private user-modify-playback-state

todoist:
  service-name: Todoist
  client-id: ${TODOIST_CLIENT_ID}
  client-secret: ${TODOIST_CLIENT_SECRET}
  redirect-uri: http://localhost:8000/auth/todoist/callback
  api-base-url: https://api.todoist.com/rest/v2
  scopes: data:read

unsplash:
  service-name: Unsplash
  client-id: ${UNSPLASH_CLIENT_ID}
  client-secret: ${UNSPLASH_CLIENT_SECRET}
  redirect-uri: ${FRONTEND_BASE_URL}/callback/unsplash
  api-base-url: https://api.unsplash.com
  scopes: write_likes+public

instagram:
  service-name: Instagram
  client-id: ${INSTAGRAM_CLIENT_ID}
  client-secret: ${INSTAGRAM_CLIENT_SECRET}
  redirect-uri: http://localhost:8000/auth/instagram/callback
  api-base-url: https://graph.instagram.com/v19.0
  scopes: user_profile,user_media

open-ai:
  service-name: OpenAI
  api-key: ${OPENAI_API_KEY}
  api-base-url: https://api.openai.com/v1
  message-limit: 20

open-weather-map:
  service-name: OpenWeather
  api-key: ${OPEN_WEATHER_MAP_API_KEY}
  api-base-url: https://api.openweathermap.org/data/2.5

encryption:
  secret-key: ${SECRET_KEY}
