server:
  port: 8000

spring:
  devtools:
    restart:
      enabled: 'false'
      poll-interval: '2s'
      quiet-period: '1s'
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@localhost:27017/start?authSource=admin
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${auth0.clientId}
            client-secret: ${auth0.clientSecret}
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/

spotify:
  service-name: Spotify
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
  redirect-uri: http://localhost:8000/widgets/spotify/auth/callback
  apiBase-url: https://api.spotify.com/v1
  scopes: user-read-currently-playing

todoist:
  service-name: Todoist
  client-id: ${TODOIST_CLIENT_ID}
  client-secret: ${TODOIST_CLIENT_SECRET}
  redirect-uri: http://localhost:8000/widgets/todoist/auth/callback
  api-base-url: https://api.todoist.com/rest/v2
  scopes: data:read

unsplash:
  service-name: Unsplash
  client-id: ${UNSPLASH_CLIENT_ID}
  client-secret: ${UNSPLASH_CLIENT_SECRET}
  redirect-uri: http://localhost:8000/widgets/unsplash/auth/callback
  api-base-url: https://api.unsplash.com
  scopes: write_likes+public

instagram:
  service-name: Instagram
  client-id: ${INSTAGRAM_CLIENT_ID}
  client-secret: ${INSTAGRAM_CLIENT_SECRET}
  redirect-uri: http://localhost:8000/widgets/instagram/auth/callback
  api-base-url: https://graph.instagram.com/v19.0
  scopes: user_profile,user_media

open-ai:
  service-name: OpenAI
  api-key: ${OPENAI_API_KEY}
  api-base-url: https://api.openai.com/v1
  message-limit: 20

nextcloud:
  service-name: Nextcloud

encryption:
  secret-key: ${SECRET_KEY}
auth0:
  domain: ${AUTH0_DOMAIN}
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}
  audience: ${AUTH0_AUDIENCE}
